---

AWSTemplateFormatVersion: "2010-09-09"
Description: >
  DevOps AWS Continuous Delivery
  Create CodePipeline continuous delivery pipeline for AWS CloudFormation stacks.
  Uses Foundation bucket artifacts to create stacks and changesets.

Parameters:
  PipelineStackName:
    Description: DevOps CD stack name
    Type: String

  ProjectName:
    Description: Project Name
    Type: String

  NameSuffix:
    Description: Stack name suffix
    Type: String

  Environment:
    Default: tst
    Description: Stack environment
    Type: String

  FoundationBucket:
    Description: Foundation S3 Bucket
    Type: String

  InfraDevBucket:
    Description: InfraDev S3 Bucket
    Type: String

  BuildArtifactsBucket:
    Description: Build S3 Bucket
    Type: String

  TemplateFileName:
    Description: Template file to build in CFn
    Type: String

  DevStackConfig:
    Description: Configuration file name for the Development stack
    Type: String

  StgStackConfig:
    Description: Configuration file name for the Staging stack
    Type: String

  ProdStackConfig:
    Description: Configuration file name for the Production stack
    Type: String

  # Github settings for Pipeline source
  GithubBranch:
    Default: develop
    Type: String

  GithubOAuthToken:
    Type: String

  GithubOwner:
    Default: dm
    Type: String

  GithubRepo:
    Default: aws-bare
    Type: String

Resources:
  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        Location: !Ref BuildArtifactsBucket
        Type: S3
      DisableInboundStageTransitions: []
      Name: !Join [ '-', [ !Ref ProjectName, !Ref NameSuffix, 'pipeline'] ]
      RoleArn: !GetAtt [RolePipeline, Arn]
      Stages:


        - Name: Source
          Actions:
            - Name: InfraDev Pipeline Source
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: 1
              Configuration:
                Branch: !Ref GithubBranch
                OAuthToken: !Ref GithubOAuthToken
                Owner: !Ref GithubOwner
                Repo: !Ref GithubRepo
              RunOrder: 1
              OutputArtifacts:
                - Name: PipelineTemplate
          - Name: TemplateConfigSources
            ActionTypeId:
              Category: Source
              Owner: AWS
              Provider: S3
              Version: '1'
            Configuration:
              S3Bucket: !Ref 'InfraDevBucket'
              S3ObjectKey:
                !Join [ '', [ 'pipeline/config/', !Ref ProjectName, '-', !Ref NameSuffix, '-', 'foundation', '.zip'] ]
            OutputArtifacts:
              - Name: TemplateSource
            RunOrder: '1'


        - Name: DevStage
          Actions:
            - Name: CreateDevStack
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: '1'
              InputArtifacts:
                - Name: PipelineTemplate
                - Name: TemplateSource
              Configuration:
                ActionMode: REPLACE_ON_FAILURE
                RoleArn: !GetAtt [RoleCfn, Arn]
                StackName: !Join [ '-', [ !Ref ProjectName, 'dev', !Ref NameSuffix, 'foundation'] ]
                TemplateConfiguration: !Sub "TemplateSource::config.dev.json"
                TemplatePath: !Sub "TemplateSource::${TemplateFileName}"
              RunOrder: '1'
            - Name: CreateChangeSet
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: '1'
              InputArtifacts:
                - Name: TemplateSource
              Configuration:
                ActionMode: CHANGE_SET_REPLACE
                RoleArn: !GetAtt [RoleCfn, Arn]
                StackName: !Join [ '-', [ !Ref ProjectName, 'stg', !Ref NameSuffix, 'foundation'] ]
                ChangeSetName: !Join [ '-', [ !Ref ProjectName, 'dev-stg', !Ref NameSuffix, 'changeset'] ]
                TemplateConfiguration: !Sub "TemplateSource::${StgStackConfig}"
                TemplatePath: !Sub "TemplateSource::${TemplateFileName}"
              RunOrder: '2'
            - Name: ApproveDevStack
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Provider: Manual
                Version: '1'
              Configuration:
                CustomData: !Sub 'Apply changeset against the Staging Stack?'
              RunOrder: '3'

        - Name: StgStage
          Actions:
            - Name: CreateChangeSet
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: '1'
              InputArtifacts:
                - Name: TemplateSource
              Configuration:
                ActionMode: CHANGE_SET_REPLACE
                RoleArn: !GetAtt [RoleCfn, Arn]
                StackName: !Join [ '-', [ !Ref ProjectName, 'stg', !Ref NameSuffix, 'foundation'] ]
                ChangeSetName: !Join [ '-', [ !Ref ProjectName, 'dev-stg', !Ref NameSuffix, 'changeset'] ]
                TemplateConfiguration: !Sub "TemplateSource::${StgStackConfig}"
                TemplatePath: !Sub "TemplateSource::${TemplateFileName}"
              RunOrder: '1'
            - Name: ApproveChangeSet
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Provider: Manual
                Version: '1'
              Configuration:
                CustomData: !Sub 'New changeset on ${ProdStackName} stack. Deploy changes?'
              RunOrder: '2'
            - Name: ExecuteChangeSet
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: '1'
              Configuration:
                ActionMode: CHANGE_SET_EXECUTE
                ChangeSetName: !Ref ChangeSetName
                RoleArn: !GetAtt [RoleCfn, Arn]
                StackName: !Ref ProdStackName
              RunOrder: '3'



        - Name: ProdStage
          Actions:
            - Name: CreateChangeSet
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: '1'
              InputArtifacts:
                - Name: TemplateSource
              Configuration:
                ActionMode: CHANGE_SET_REPLACE
                RoleArn: !GetAtt [RoleCfn, Arn]
                StackName: !Join [ '-', [ !Ref ProjectName, 'prd', !Ref NameSuffix, 'foundation'] ]
                ChangeSetName: !Ref ChangeSetName
                TemplateConfiguration: !Sub "TemplateSource::${ProdStackConfig}"
                TemplatePath: !Sub "TemplateSource::${TemplateFileName}"
              RunOrder: '1'
            - Name: ApproveChangeSet
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Provider: Manual
                Version: '1'
              Configuration:
                CustomData: !Sub 'New changeset on ${ProdStackName} stack. Deploy changes?'
              RunOrder: '2'
            - Name: ExecuteChangeSet
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: '1'
              Configuration:
                ActionMode: CHANGE_SET_EXECUTE
                ChangeSetName: !Ref ChangeSetName
                RoleArn: !GetAtt [RoleCfn, Arn]
                StackName: !Ref ProdStackName
              RunOrder: '3'

  RoleCfn:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: ['sts:AssumeRole']
          Effect: Allow
          Principal:
            Service: [cloudformation.amazonaws.com]
        Version: '2012-10-17'
      Path: /
      Policies:
        - PolicyName: RoleCfn
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - 'ec2:*'
                Effect: Allow
                Resource: '*'

  RolePipeline:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: ['sts:AssumeRole']
          Effect: Allow
          Principal:
            Service: [codepipeline.amazonaws.com]
        Version: '2012-10-17'
      Path: /
      Policies:
        - PolicyName: RolePipeline
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                - 'cloudformation:CreateChangeSet'
                - 'cloudformation:CreateStack'
                - 'cloudformation:DeleteChangeSet'
                - 'cloudformation:DeleteStack'
                - 'cloudformation:DescribeChangeSet'
                - 'cloudformation:DescribeStacks'
                - 'cloudformation:ExecuteChangeSet'
                - 'cloudformation:SetStackPolicy'
                - 'cloudformation:UpdateStack'
                - 'iam:PassRole'
                - 's3:*'
                Effect: Allow
                Resource: '*'
