---

Description: Application Deployment on ECS
AWSTemplateFormatVersion: 2010-09-09

Parameters:
  AppName:
    Description: Application name
    Type: String

  AppStackName:
    Description: App stack name
    Type: String

  BuildArtifactsBucket:
    Description: Build Artifacts S3 Bucket
    Type: String

  ContainerMemory:
    Default: 256
    Type: Number

  ContainerPort:
    Default: 8080
    Type: Number

  Environment:
    Description: Stack environment
    Type: String

  EcsClusterSize:
    Type: Number
    Default: 1

  FoundationStackName:
    Description: Foundation stack name
    Type: String

  InfraDevBucket:
    Description: App S3 Bucket
    Type: String

  ProjectName:
    Description: Project name
    Type: String

  PublicDomain:
    Description: Domain Name to create new NS subdomain entries
    Type: String

  PublicFQDN:
    Description: Public Fully Qualified Domain Name
    Type: String

  Region:
    Default: us-east-1
    Description: Region
    Type: String

  RepositoryBranch:
    Default: master
    Description: Branch to deploy in CD Pipeline
    Type: String

  SshKeyName:
    Type: AWS::EC2::KeyPair::KeyName

  UserName:
    Description: User FirstLastName
    Type: String

Resources:
  CodeCommitRepo:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: !Join [ '-', [ !Ref ProjectName, !Ref UserName, !Ref AppName ] ]
      RepositoryDescription: !Sub "Project repository for ${ProjectName}"

  LoadBalancer:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${InfraDevBucket}/${Environment}/templates/load-balancer.yaml
      Parameters:
        AppStackName: !Ref AppStackName
        FoundationStackName: !Ref FoundationStackName
        PublicDomain: !Ref PublicDomain
        PublicFQDN: !Ref PublicFQDN

  Cluster:
    DependsOn:
      - LoadBalancer
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${InfraDevBucket}/${Environment}/templates/ecs-cluster.yaml
      Parameters:
        AppStackName: !Ref AppStackName
        FoundationStackName: !Ref FoundationStackName
        SourceSecurityGroup: !GetAtt LoadBalancer.Outputs.SecurityGroup
        SshKeyName: !Ref SshKeyName

  BookitServerService:
    DependsOn:
      - Cluster
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${InfraDevBucket}/${Environment}/templates/service.yaml
      Parameters:
        AppName: !Ref AppName
        AppStackName: !Ref AppStackName
        BuildArtifactsBucket: !Ref BuildArtifactsBucket
        Cluster: !GetAtt Cluster.Outputs.ClusterName
        ContainerMemory: !Ref ContainerMemory
        ContainerPort: !Ref ContainerPort
        InfraDevBucket: !Ref InfraDevBucket
        RepositoryName: !GetAtt CodeCommitRepo.Name
        RepositoryBranch: !Ref RepositoryBranch
        TargetGroup: !GetAtt LoadBalancer.Outputs.TargetGroup
        Repository: !Ref Repository

Outputs:

  LoadBalancerUrl:
    Description: URL of the load balancer for the sample service.
    Value: !GetAtt LoadBalancer.Outputs.ServiceUrl
