---

Description: Service definition
AWSTemplateFormatVersion: 2010-09-09

Parameters:
  AppName:
    Description: Application name
    Type: String

  AppStackName:
    Type: String

  Cluster:
    Type: String

  ContainerMemory:
    Default: 256
    Type: Number

  ContainerPort:
    Default: 8080
    Type: Number

  DesiredCount:
    Type: Number
    Default: 0

  Repository:
    Type: String

  Tag:
    Type: String
    Default: latest

  TargetGroup:
    Type: String

Resources:
  ECSServiceRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument: |
        {
            "Statement": [{
                "Effect": "Allow",
                "Principal": { "Service": [ "ecs.amazonaws.com" ]},
                "Action": [ "sts:AssumeRole" ]
            }]
        }
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceRole

  Service:
    Type: AWS::ECS::Service
    DependsOn:
      - TaskDefinition
      - ECSServiceRole
    Properties:
      Cluster: !Ref Cluster
      Role: !Ref ECSServiceRole
      DesiredCount: !Ref DesiredCount
      TaskDefinition: !Ref TaskDefinition
      LoadBalancers:
        - ContainerName: !Ref AppStackName
          ContainerPort: !Ref ContainerPort
          TargetGroupArn: !Ref TargetGroup

  TaskDefinitionServiceRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument: |
        {
            "Statement": [{
                "Effect": "Allow",
                "Principal": { "Service": [ "ecs-tasks.amazonaws.com" ]},
                "Action": [ "sts:AssumeRole" ]
            }]
        }
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Resource: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${AppStackName}-*
                Effect: Allow
                Action:
                  - ssm:GetParameters

  TaskDefinition:
    DependsOn: TaskDefinitionServiceRole
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub ${AppStackName}-deployment
      TaskRoleArn: !Ref TaskDefinitionServiceRole
      ContainerDefinitions:
        - Name: !Ref AppStackName
          Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${Repository}:${Tag}
          Essential: true
          Memory: !Ref ContainerMemory
          PortMappings:
            - ContainerPort: !Ref ContainerPort
              HostPort: 0
          Environment:
            - Name: Tag
              Value: !Ref Tag
